### ISSUE TITLE
How to Contribute to Datasets

### ISSUE THREAD

**Issue by pardeep-singh** [pacman100/openhathi_instruct#3]
Hey @pacman100 I would like to work on the following task:

> Transcription of Indian Hindi Youtube videos and Hindi podcasts from influencers to get Hindi/Hinglish datasets

Can you please share the instructions on how we can share this dataset?

**Comment by charchit7** [comment]
Same here. :)

**Comment by pardeep-singh** [comment]
Closing this. This is what I did:

- Added my name on [this sheet](https://docs.google.com/spreadsheets/d/15TVCqWisQW_goCjd5vSpEArmJxm04dB0213BOP6EmvY/edit#gid=0) for dataset task I was working on
- Shared the dataset on Discord channel
